version: "3.0"
nlu:
- intent: apply_for_course
  examples: |
    - I want to apply for this course
    - can i apply for this course?
- intent: visit_campus
  examples: |
    - tell me about northumbria campus
    - visit campus
- intent: buildings
  examples: |
    - buildings
    - i want to know about buildings
- intent: show_building_on_map
  examples: |
    - show on campus map
    - show on map
- intent: calendar
  examples: |
    - show calendar
    - calendar dates
- intent: building_codes_option
  examples: |
    - building code
    - location codes
    - building codes
- intent: building_location_option
  examples: |
    - building locations
    - buildings location
    - building location
- intent: lecturers_option
  examples: |
    - lecturer
    - show me lecturers
    - lecturers
- intent: course_fees
  examples: |
    - what are the fees
    - how much does the course cost
    - how much is it for uk students
    - fees
- intent: university_accommodation
  examples: |
    - what accomodation is there
    - how much is university accomodation
    - do you offer accomodation
    - I need accommodation
- intent: open_days
  examples: |
    - i want to come to campus
    - campus open days
    - When are the opens days
    - when i can i visit campus
- intent: campus_map
  examples: |
    - northumbria university map
    - northumbria map
    - Show me the campus map
    - campus map
- intent: show_map
  examples: |
    - show me map
    - show map
    - show me the map
    - show me the map for the buildings
- intent: choose_modules_for_specific_course
  examples: |
    - show me year [3](year) modules for [Computer Science](course)
    - [computer network security] modules
    - show me year [4](year) modules for [Computer Science](course)
    - show me year [1](year) modules for [Computer Science](course)
    - show me year [2](year) modules for [Computer Science](course)
- intent: university_facilities
  examples: |
    - does northumbria have a computer building
    - does northumbria have a library
    - What facilities do you offer
    - university facilities
    - does northumbria have a vr room
- intent: thank
  examples: |
    - sound
    - thank you
    - cool
    - cheers
    - ty
    - thnx
    - thanks
- intent: get_directions
  examples: |
    - show directions
    - how do i get to building
    - directions
    - get directions
    - show on maps
    - show directions on maps
    - show directions on google maps
- intent: lecturer_email
  examples: |
    - What is [Jeremy Ellman](lecturer) email
    - show me Dr [Christina Vasiliou](lecturer) email?
    - what is Dr [Jeremy Ellman](lecturer) email?
    - whats Dr [Kay Rogage](lecturer) email?
    - [christina vasiliou](lecturer) email?
    - [jeremy ellman](lecturer) email
    - [alex thompson](lecturer) email
- intent: interest_in_course
  examples: |
    - course
    - which courses are there
    - I want to know about a course
    - What courses
    - a course
    - tell me about the available courses
    - Im interested in taking a course
- intent: entry_requirements
  examples: |
    - do i have the right grades
    - what grades do i need
    - what do i need
    - are my grades enough
    - which grades do i need
    - entry requirements
    - requirements
- intent: entry_requirements_for_course
  examples: |
    - entry requirements for [computer network security](course)
    - what are the entry requirements for [computer Networks and cyber security bsc](course)
    - show me entry requirements for [computer and digital forensics bsc](course)
    - show me entry requirements for [Computer Science](course)
    - what are entry requirements for [Computer Science with Web Development BSc](course)
    - [Computer Science with Games Development BSc](course) entry requirements
    - entry requirements for [computer networks](course)
    - entry requirements for [Computer Science with Artificial Intelligence BSc](course)
- intent: my_student_type
  examples: |
    - [aspiring](student_type)
    - [existing](student_type)
    - [existing](student_type) student
    - [Existing](student_type)
    - [aspiring](student_type) student
    - I am an [aspiring](student_type) student
    - I am an [existing](student_type) student
    - a [aspiring](student_type)
    - a [existing](student_type)
- intent: get_directions_from_another_building
  examples: |
    - how long to get from [EBA](building_code) to [city campus east](building_name_destination)
    - distance from [CIS](building_code) to [CCE1](building_code_destination)
    - [cis](building_code) to [elison building c block](building_name_destination)
    - how long to get to [EBA](building_code_destination) from [cce1](building_code)
    - how long does it take to get from [EBA](building_code) to [CCE1](building_code_destination)
    - distance from [Sutherland](building_name) to [Ellison Building A Block](building_name_destination)
    - [Sandyford Building](building_name) to [Northumberland Building](building_name_destination)
    - show [Lipman Building](building_name) and [Squires Workshops](building_name_destination)
    - [CIS](building_code) to [EBB](building_code_destination)
    - how long will it take me to get from [City Campus East 2](building_name) to [CIS Building](building_name_destination)
    - show [CIS](building_code) and [EBB](building_code_destination)
    - how long does it take to get from [City Campus East 1](building_name) to [Wynne-Jones Building](building_name_destination)
- intent: bot_challenge
  examples: |
    - you are not a human are you?
    - you are not a human are you
    - am I talking to a bot?
    - you are not a human
    - you are a bot
    - you are not a human, are you?
    - you are not a human, are you
    - are you a human?
    - your a bot
    - who are you?
    - are you a bot?
    - am I talking to a human?
    - youre a bot
    - whom are you?
- intent: show_modules
  examples: |
    - modules to show me
    - Please show me modules.
    - modules
    - [Computer Science](course) modules
    - show the modules
    - which modules are there
    - Modules, please.
    - show me [Computer Science](course) modules
    - what modules are on this course
    - the module
    - show me modules
    - Show me the modules
    - show modules
- intent: choose_module_type
  examples: |
    - [2](year): Show [EBA](building_code) on Ma
    - year [3](year)
    - [2](year): Show [CCE1](building_code) on Ma
    - Year [2](year) Modules
    - [2](year)
    - year [4](year)
    - [2](year): Show on Ma
    - year [1](year)
    - year [2](year)
    - [3](year)
    - [all](year) Modules
    - Year [1](year) Modules
    - Year [4](year) Modules
    - [2](year): [City](course) Campus East
- intent: building_name
  examples: |
    - what building is [CCE2](building_code)
    - [SUB](building_code)
    - what is [SQ](building_code)
    - [EBA](building_code)
    - [LIP](building_code)
    - [CIS](building_code)
    - [cce1](building_code)
    - what is [NB](building_code)
    - what building is [EBB](building_code)
    - what is [EBD](building_code)
    - what building is [EBE](building_code)
    - what is [EBA](building_code)
    - what is [WJB](building_code)
    - [EBC](building_code)
    - what building is [SQW](building_code)
- intent: deny
  examples: |
    - refuse
    - definitely not
    - nah!
    - no way!
    - nope
    - negative
    - nah
    - n
    - I don't think so
    - disprove
    - never
    - no
    - not really
    - no way
    - turn down
    - nop
- intent: get_directions_from_my_location
  examples: |
    - how long from me to get to [Squires Workshops](building_name)
    - how long to get to [Wynne Jones](building_name)
    - how do i get to [lipman](building_name)
    - how long will it take me to get to [EBA](building_code)
    - how do i get to [Lipman Building](building_name)
    - directions from me to [city campus east](building_name)
    - how do i get to [Sandyford Building](building_name)
    - how far away is [Sutherland](building_name)
    - how long will it take me to get to [EBB](building_code)
    - how far away is [CIS](building_code)
    - my location to [City Campus East 2](building_name)
    - my location to [cce1](building_code)
    - how far away is [Squire workshops](building_name)
    - my location to [EBA](building_code)
    - how long will it take me to get to [CCE1](building_code)
    - how long wll it take me to get to [EBB](building_code)
- intent: affirm
  examples: |
    - that sounds good
    - yeah
    - yea
    - okie
    - assert
    - of course
    - y
    - k
    - affirm
    - yess
    - okey
    - okay
    - ok
    - yes!
    - ye
    - confirm
    - yes
- intent: select_course
  examples: |
    - [game development](course)
    - Do you offer [Computer Science](course)?
    - [network security](course)
    - [computer and digital forensics bsc](course)
    - [Computer Science with Artificial Intelligence BSc](course)
    - [artificial intelligence](course)
    - [computer science with web development bsc](course)
    - [computer and digital forensics](course)
    - [Computer Science BSc](course)
    - [Computer and Digital Forensics BSc](course)
    - [computer science with artificial intelligence bsc](course)
    - [digital forensics](course)
    - [computer science bsc](course)
    - [Computer Networks and Cyber Security BSc](course)
    - Tell me about [Computer Science BSc](course)
    - [games development](course)
    - [Computer Science with Web Development BSc](course)
    - [cyber security](course)
    - [computer science with games development bsc](course)
- intent: building_location
  examples: |
    - where is [SUB](building_code)
    - where is [Ellison Building D Block](building_name)
    - wheres [EBE](building_code)
    - where is [Ellison Building B Block](building_name)
    - wheres [WJB](building_code)
    - wheres [SQX](building_code)
    - where is [Lipman Building](building_name)
    - where is [City Campus East 1](building_name)
    - wheres [Wynne-Jones Building](building_name)
    - where is [SQ](building_code)
    - where is [Squires Building](building_name)
    - where is [EBB](building_code)
    - wheres [EBC](building_code)
    - where is [CCE1](building_code)
    - wheres [Ellison Building A Block](building_name)
    - where is [Sandyford Building](building_name)
    - where is [Sutherland](building_name)
    - wheres [SQW](building_code)
    - where is [EBD](building_code)
    - wheres [Ellison Building C Block](building_name)
    - where is [SAN](building_code)
    - wheres [City Campus East 2](building_name)
    - wheres [CCE2](building_code)
    - where is [CIS Building](building_name)
    - where is [CIS](building_code)
    - wheres [EBA](building_code)
    - wheres [Ellison Building E Block](building_name)
- intent: goodbye
  examples: |
    - bye -bye
    - g2g
    - im going now
    - c u later
    - cu later
    - cu l8r
    - seee you
    - by by
    - so long
    - good night
    - cheerio
    - see you around
    - bye-bye
    - got to go
    - later
    - toodle-oo
    - be seeing you
    - bye
    - goodbye
    - see you another day
    - have a nice day
    - ciao
    - byee
    - cee you later
    - ive got to go now
    - see you later
    - bye bye
    - byeee
- intent: greet
  examples: |
    - good afternoon
    - hi-ya
    - heya
    - hey
    - greetings
    - hey dude
    - let's go
    - nice to meet you
    - hi welcome
    - greeting
    - heloo
    - moin
    - heyaa
    - bonjour
    - howde
    - good morning
    - hey friend
    - goodevening
    - hello there
    - goodmorning
    - gretings
    - gud day
    - welcome
    - how goes it
    - what's happening
    - what's up
    - hey ya
    - good evening
    - good day.
    - helo
- intent: give_name
  examples: |
    - im [alex](name)
    - my name is [rachel](name)
    - name is [alex](name)
    - im [emma](name)
    - i'm [yolinda](name)
    - [yolinda](name)
    - [rachel](name)
    - i'm [vincent](name)
    - name is [pete](name)
    - [vincent](name)
    - i am [rachel](name)
    - name is [rachel](name)
    - i am [vincent](name)
    - [pete](name)
    - i'm [pete](name)
    - my name is [emma](name)
    - my name is [yolinda](name)
    - name is [yolinda](name)
    - name is [vincent](name)
    - i am [emma](name)
    - [Alex](name)
    - i am [alex](name)
    - i am [yolinda](name)
    - i'm [rachel](name)
    - i'm [alex](name)
    - i am [pete](name)
    - my name is [alex](name)
    - my name is [vincent](name)
    - im [pete](name)
    - im [yolinda](name)
